export const YUGIOH_FILTER_SECTIONS = [
  {
    id: "rarity",
    label: "Rarity",
    options: [
      "Common / Short Print",
      "Rare",
      "Super Rare",
      "Ultra Rare",
      "Secret Rare",
      "Prismatic Secret Rare",
      "Gold Rare",
      "Gold Secret Rare",
      "Premium Gold Rare",
      "Shatterfoil Rare",
      "Mosaic Rare",
      "Collector's Rare",
      "Prismatic Collector's Rare",
      "Starfoil Rare",
      "Ultimate Rare",
      "Starlight Rare",
      "Ghost Rare",
      "Gold Ghost Rare",
      "Platinum Secret Rare",
      "Quarter Century Secret Rare",
      "Prismatic Ultimate Rare",
      "Pharaoh's Rare",
      "Duel Terminal Rare",
      "Parallel Rare",
    ],
  },
  {
    id: "condition",
    label: "Condition",
    options: [
      "Near Mint 1st Edition",
      "Lightly Played 1st Edition",
      "Moderately Played 1st Edition",
      "Heavily Played 1st Edition",
      "Damaged 1st Edition",
      "Near Mint Limited",
      "Lightly Played Limited",
      "Moderately Played Limited",
      "Heavily Played Limited",
      "Damaged Limited",
      "Near Mint Unlimited",
      "Lightly Played Unlimited",
      "Moderately Played Unlimited",
      "Heavily Played Unlimited",
      "Damaged Unlimited",
    ],
  },
  {
    id: "printing",
    label: "Printing",
    options: ["1st Edition", "Unlimited", "Limited"],
  },
];

